# Generated by Django 5.0.14 on 2026-03-05 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('repo_name', models.CharField(max_length=100, verbose_name='Repository adı')),
                ('repo_url', models.URLField(blank=True, verbose_name='Repository URL')),
                ('repo_full_name', models.CharField(blank=True, max_length=200, verbose_name='Tam ad (owner/repo)')),
                ('status', models.CharField(choices=[('pending', 'Gözləmədə'), ('creating', 'Yaradılır'), ('created', 'Yaradıldı'), ('failed', 'Uğursuz'), ('archived', 'Arxivləşdirildi')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Xəta mesajı')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Tələbə Repository',
                'verbose_name_plural': 'Tələbə Repositoryləri',
                'db_table': 'github_student_repository',
            },
        ),
    ]
