# Generated by Django 5.0.14 on 2026-03-05 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrepository',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL, verbose_name='Tələbə'),
        ),
        migrations.AlterUniqueTogether(
            name='studentrepository',
            unique_together={('student', 'course')},
        ),
    ]
