# Generated by Django 5.0.14 on 2026-03-05 13:09

import core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('material_type', models.CharField(choices=[('video', 'Video (YouTube)'), ('text', 'Mətn dərsi'), ('pdf', 'PDF sənəd'), ('code', 'Kod nümunəsi'), ('task', 'Tapşırıq'), ('external', 'Xarici link')], default='video', max_length=20, verbose_name='Material növü')),
                ('youtube_url', models.URLField(blank=True, validators=[core.validators.validate_youtube_url], verbose_name='YouTube linki')),
                ('youtube_video_id', models.CharField(blank=True, max_length=20, verbose_name='YouTube video ID')),
                ('youtube_title', models.CharField(blank=True, max_length=255, verbose_name='Video başlığı')),
                ('youtube_duration', models.CharField(blank=True, max_length=20, verbose_name='Video müddəti')),
                ('content', models.TextField(blank=True, verbose_name='Məzmun (rich text)')),
                ('file', models.FileField(blank=True, upload_to='lesson_files/', verbose_name='Fayl')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='Pulsuz önizləmə')),
            ],
            options={
                'verbose_name': 'Dərs',
                'verbose_name_plural': 'Dərslər',
                'db_table': 'courses_lesson',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'db_table': 'courses_module',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='courses.category', verbose_name='Üst kateqoriya')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
                'db_table': 'courses_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('cover_image', models.ImageField(blank=True, upload_to='course_images/', verbose_name='Örtük şəkli')),
                ('status', models.CharField(choices=[('draft', 'Hazırlanır'), ('active', 'Aktiv'), ('archived', 'Arxiv')], default='draft', max_length=20, verbose_name='Status')),
                ('level', models.CharField(choices=[('beginner', 'Başlanğıc'), ('intermediate', 'Orta'), ('advanced', 'İrəliləmiş')], default='beginner', max_length=20, verbose_name='Səviyyə')),
                ('objectives', models.TextField(blank=True, verbose_name='Kurs məqsədləri')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Ön şərtlər')),
                ('duration_weeks', models.PositiveIntegerField(default=12, verbose_name='Müddət (həftə)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'db_table': 'courses_course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma tarixi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Qeydiyyat',
                'verbose_name_plural': 'Qeydiyyatlar',
                'db_table': 'courses_enrollment',
                'ordering': ['-created_at'],
            },
        ),
    ]
