# Generated by Django 5.0.14 on 2026-03-05 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('type', models.CharField(choices=[('quiz', 'Test'), ('homework', 'Ev tapşırığı'), ('project', 'Layihə'), ('exam', 'İmtahan')], default='homework', max_length=20, verbose_name='Növ')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bal (100 üzərindən)')),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Maksimum bal')),
                ('feedback', models.TextField(blank=True, verbose_name='Rəy')),
                ('submission_url', models.URLField(blank=True, verbose_name='GitHub / Fayl linki')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Son tarix')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Göndərilmə tarixi')),
            ],
            options={
                'verbose_name': 'Qiymətləndirmə',
                'verbose_name_plural': 'Qiymətləndirmələr',
                'db_table': 'assessments_assessment',
                'ordering': ['-created_at'],
            },
        ),
    ]
