# Generated by Django 5.0.14 on 2026-03-05 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('lessons_per_week', models.PositiveSmallIntegerField(verbose_name='Həftəlik dərs sayı')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Aylıq məbləğ (AZN)')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('paused', 'Dayandırılıb'), ('cancelled', 'Ləğv edildi')], default='active', max_length=20, verbose_name='Status')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Subscription ID')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='Növbəti ödəniş tarixi')),
            ],
            options={
                'verbose_name': 'Aylıq Abunə',
                'verbose_name_plural': 'Aylıq Abunələr',
                'db_table': 'payments_monthly_subscription',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Məbləğ (AZN)')),
                ('status', models.CharField(choices=[('pending', 'Gözləmədə'), ('completed', 'Tamamlandı'), ('failed', 'Uğursuz'), ('refunded', 'Geri qaytarıldı'), ('overdue', 'Gecikib'), ('cancelled', 'Ləğv edildi')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe (Kart)'), ('bank_transfer', 'Bank Köçürməsi'), ('cash', 'Nağd'), ('online', 'Online (e-Manat)')], default='stripe', max_length=20, verbose_name='Ödəniş üsulu')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe PaymentIntent ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Faktura nömrəsi')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıqlama')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ödəniş tarixi')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Son ödəniş tarixi')),
            ],
            options={
                'verbose_name': 'Ödəniş',
                'verbose_name_plural': 'Ödənişlər',
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
