# Generated by Django 5.0.6 on 2026-03-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysubscription',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='monthlysubscription',
            name='epoint_subscription_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ePoint Subscription ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='epoint_order_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ePoint Order ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='epoint_transaction_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ePoint Transaction ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('epoint', 'ePoint (Online kart)'), ('bank_transfer', 'Bank Köçürməsi'), ('cash', 'Nağd'), ('online', 'Online')], default='epoint', max_length=20, verbose_name='Ödəniş üsulu'),
        ),
    ]
