# Generated by Django 5.0.14 on 2026-03-05 13:09

import core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('role', models.CharField(choices=[('teacher', 'Müəllim'), ('student', 'Tələbə')], default='student', max_length=10, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[core.validators.validate_phone_number], verbose_name='Telefon')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Profil şəkli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin heyəti')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Qeydiyyat tarixi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'İstifadəçi',
                'verbose_name_plural': 'İstifadəçilər',
                'db_table': 'users_user',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('active', 'Aktiv'), ('inactive', 'Passiv'), ('frozen', 'Dondurulmuş'), ('graduated', 'Bitirmiş')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_model', models.CharField(choices=[('monthly', 'Aylıq abunə'), ('per_lesson', 'Dərs əsaslı')], default='monthly', max_length=20, verbose_name='Ödəniş modeli')),
                ('lessons_per_week', models.PositiveSmallIntegerField(default=2, verbose_name='Həftəlik dərs sayı')),
                ('github_username', models.CharField(blank=True, max_length=100, validators=[core.validators.validate_github_username], verbose_name='GitHub istifadəçi adı')),
                ('github_repo_url', models.URLField(blank=True, verbose_name='GitHub repo URL')),
                ('timezone', models.CharField(default='Asia/Baku', max_length=50, verbose_name='Vaxt zonası')),
                ('education_level', models.CharField(blank=True, max_length=100, verbose_name='Təhsil səviyyəsi')),
                ('goals', models.TextField(blank=True, verbose_name='Öyrənmə məqsədləri')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='Müəllim qeydləri (gizli)')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Status dəyişikliyi tarixi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Tələbə Profili',
                'verbose_name_plural': 'Tələbə Profilləri',
                'db_table': 'users_student_profile',
            },
        ),
    ]
