# Generated by Django 5.0.6 on 2026-03-08 16:27

import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, validators=[core.validators.validate_phone_number], verbose_name='Telefon (Whatsapp)')),
                ('course_package', models.CharField(choices=[('front_end', 'Front End Development'), ('back_end', 'Back End Development'), ('full_stack', 'Full Stack Development'), ('api_driven', 'API (API Driven Development)'), ('dsa', 'DSA (Data Structure and Algorithms)'), ('cyber_security', 'Cyber Security'), ('project_mentorship', 'Project Mentorship'), ('other', 'Digər')], max_length=30, verbose_name='Dərs paketi')),
                ('other_course', models.CharField(blank=True, max_length=200, verbose_name='Digər dərs paketi (əgər "Digər" seçilibsə)')),
                ('payment_receipt', models.CharField(blank=True, max_length=500, verbose_name='Ödəmə məlumatı')),
                ('preferred_start_date', models.DateField(verbose_name='Başlamaq istədiyi tarix')),
                ('github_profile_url', models.URLField(blank=True, verbose_name='GitHub profil linki')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('approved', 'Təsdiqləndi'), ('rejected', 'Rədd edildi')], default='pending', max_length=20, verbose_name='Status')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='Müəllim qeydləri')),
                ('approved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request', to=settings.AUTH_USER_MODEL, verbose_name='Yaradılmış istifadəçi')),
            ],
            options={
                'verbose_name': 'Qeydiyyat müraciəti',
                'verbose_name_plural': 'Qeydiyyat müraciətləri',
                'db_table': 'users_registration_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
