# Generated by Django 5.0.6 on 2026-03-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='lessons_per_week',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Həftəlik dərs sayı'),
        ),
    ]
