# Generated by Django 5.0.14 on 2026-03-05 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('subject', models.CharField(max_length=200, verbose_name='Mövzu')),
                ('status', models.CharField(choices=[('open', 'Açıq'), ('in_progress', 'İşlənir'), ('resolved', 'Həll edildi'), ('closed', 'Bağlı')], default='open', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Aşağı'), ('medium', 'Orta'), ('high', 'Yüksək'), ('urgent', 'Təcili')], default='medium', max_length=10, verbose_name='Prioritet')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Həll tarixi')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Ticketlər',
                'db_table': 'support_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('body', models.TextField(verbose_name='Mesaj')),
                ('is_from_teacher', models.BooleanField(default=False, verbose_name='Müəllimdəndir')),
            ],
            options={
                'verbose_name': 'Ticket Mesajı',
                'verbose_name_plural': 'Ticket Mesajları',
                'db_table': 'support_ticket_message',
                'ordering': ['created_at'],
            },
        ),
    ]
