# Generated by Django 5.0.14 on 2026-03-05 13:09

import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('lesson_type', models.CharField(choices=[('standard', 'Standart dərs'), ('trial', 'Sınaq dərsi'), ('consultation', 'Məsləhət'), ('review', 'Təkrar dərs')], default='standard', max_length=20, verbose_name='Dərs növü')),
                ('status', models.CharField(choices=[('pending', 'Gözləmədə'), ('confirmed', 'Təsdiqləndi'), ('completed', 'Tamamlandı'), ('cancelled', 'Ləğv edildi'), ('no_show', 'Görünmədi'), ('rescheduled', 'Yenidən planlandı')], default='pending', max_length=20, verbose_name='Status')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Mövzu')),
                ('student_notes', models.TextField(blank=True, verbose_name='Tələbə qeydləri')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='Müəllim qeydləri')),
                ('meet_link', models.URLField(blank=True, verbose_name='Google Meet linki')),
                ('recording_url', models.URLField(blank=True, verbose_name='Qeyd URL')),
                ('price', models.DecimalField(decimal_places=2, default=25.0, max_digits=8, verbose_name='Qiymət (AZN)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödənilib')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma tarixi')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Ləğvetmə tarixi')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Ləğvetmə səbəbi')),
            ],
            options={
                'verbose_name': 'Rezervasiya',
                'verbose_name_plural': 'Rezervasiyalar',
                'db_table': 'bookings_booking',
                'ordering': ['-slot__start_time'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('start_time', models.DateTimeField(validators=[core.validators.validate_future_datetime], verbose_name='Başlama vaxtı')),
                ('end_time', models.DateTimeField(verbose_name='Bitmə vaxtı')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Reserv edilib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
            ],
            options={
                'verbose_name': 'Əlçatan Slot',
                'verbose_name_plural': 'Əlçatan Slotlar',
                'db_table': 'bookings_availability_slot',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['start_time', 'is_reserved'], name='bookings_av_start_t_153fa1_idx'), models.Index(fields=['is_reserved', 'is_active'], name='bookings_av_is_rese_244e8d_idx')],
            },
        ),
    ]
