# Generated by Django 5.0.14 on 2026-03-05 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='courses.course', verbose_name='Kurs'),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='bookings.availabilityslot', verbose_name='Vaxt slotu'),
        ),
    ]
