# Generated by Django 5.0.6 on 2026-03-11 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Bazar ertəsi'), (1, 'Çərşənbə axşamı'), (2, 'Çərşənbə'), (3, 'Cümə axşamı'), (4, 'Cümə'), (5, 'Şənbə'), (6, 'Bazar')], verbose_name='Həftənin günü')),
                ('start_time', models.TimeField(verbose_name='Başlama saatı')),
                ('end_time', models.TimeField(verbose_name='Bitmə saatı')),
                ('slot_duration', models.PositiveSmallIntegerField(default=60, verbose_name='Slot müddəti (dəqiqə)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
            ],
            options={
                'verbose_name': 'Həftəlik Cədvəl',
                'verbose_name_plural': 'Həftəlik Cədvəllər',
                'db_table': 'bookings_weekly_schedule',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('day_of_week', 'start_time')},
            },
        ),
    ]
