# Generated by Django 5.0.14 on 2026-03-05 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('type', models.CharField(choices=[('booking_confirmed', 'Rezervasiya təsdiqləndi'), ('booking_cancelled', 'Rezervasiya ləğv edildi'), ('lesson_reminder', 'Dərs xatırlatması'), ('payment_due', 'Ödəniş müddəti'), ('payment_received', 'Ödəniş alındı'), ('payment_overdue', 'Gecikmiş ödəniş'), ('repo_created', 'GitHub repo yaradıldı'), ('general', 'Ümumi')], default='general', max_length=40, verbose_name='Növ')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('message', models.TextField(verbose_name='Məzmun')),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunub')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Əlavə məlumat')),
            ],
            options={
                'verbose_name': 'Bildiriş',
                'verbose_name_plural': 'Bildirişlər',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
